[tool.black]
line-length = 110
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
combine_as_imports = true
include_trailing_comma = true
line_length = 110

[tool.flake8]
max-line-length = 110

[tool.pylint]
max-line-length=110
disable=["C0114", "C0116", "C0115", "W0511", "R1710", "R0903", "W0223", "R0913", "R0901", "R1705"]
