# Generated by Django 4.2.6 on 2023-10-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("currency_id", models.CharField(max_length=50, unique=True)),
                ("number_code", models.CharField(max_length=50)),
                ("char_code", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=6)),
                ("prev_value", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="currency.currency",
                    ),
                ),
                (
                    "prev_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_value",
                        to="currency.currencyrate",
                    ),
                ),
            ],
        ),
    ]
