# Generated by Django 4.2.6 on 2023-10-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_alter_currencyrate_prev_rate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currencyrate",
            options={"ordering": ["-rate_date"]},
        ),
    ]
