# Generated by Django 4.2.6 on 2023-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0004_alter_currencyrate_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="prev_value",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
