# Generated by Django 4.2.6 on 2023-10-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0005_alter_currencyrate_prev_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyrate",
            name="value",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
