# Generated by Django 4.2.6 on 2023-10-11 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("currency", "0007_alter_currencyrate_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="currency.currency"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_thresholds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("currency", "user")},
            },
        ),
    ]
